### ISSUE TITLE
[BUG] terracli keys add panics

### ISSUE THREAD

**Issue by faltynmateusz** [terra-money/core#523]
**Describe the bug**
Trying to run a validator node on tequila-0004 following block42's [guide](https://medium.com/block42-blockchain-company/how-to-setup-a-terra-luna-validator-node-860d8ea7aea2) on terrad version `0.4.6-5-g5860232`. Successfully fully synced node. 

I get the following when trying to create a wallet:

```
panic: No such interface “org.freedesktop.DBus.Properties” on object at path /

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.writeInfo(0x1626fc8, 0x1626fc0, 0xc00006baa0, 0x1, 0x1, 0xc00006bb
20, 0x1, 0x1, 0x17747f8, 0xc0002b9d40, ...)
/home/faltyn/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.3/crypto/keys/keyring.go:478 +0x39c
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.writeLocalKey(0x1626fc8, 0x1626fc0, 0xc00006baa0, 0x1, 0x1, 0xc000
06bb20, 0x1, 0x1, 0x17747f8, 0xc0002b9d40, ...)
/home/faltyn/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.3/crypto/keys/keyring.go:464 +0x193
github.com/cosmos/cosmos-sdk/crypto/keys.baseKeybase.CreateAccount(0x1626fc8, 0x1626fc0, 0xc00006baa0, 0x1, 0x1, 0xc00006b
b20, 0x1, 0x1, 0x1765fd0, 0xc000f14050, ...)
/home/faltyn/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.3/crypto/keys/keybase_base.go:171 +0x1a2
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.CreateAccount(...)
/home/faltyn/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.3/crypto/keys/keyring.go:106
github.com/cosmos/cosmos-sdk/client/keys.RunAddCmd(0xc000fbb600, 0xc00022dab0, 0x1, 0x1, 0x1784198, 0xc000088050, 0xc0002b
14a0, 0xc0000cbc40, 0x5ec997)
/home/faltyn/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.3/client/keys/add.go:277 +0x782
github.com/cosmos/cosmos-sdk/client/keys.runAddCmd(0xc000fbb600, 0xc00022dab0, 0x1, 0x1, 0x0, 0x0)
/home/faltyn/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.39.3/client/keys/add.go:99 +0x170
github.com/spf13/cobra.(*Command).execute(0xc000fbb600, 0xc00022da90, 0x1, 0x1, 0xc000fbb600, 0xc00022da90)
/home/faltyn/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001f5600, 0xc0000cbe68, 0x865a25, 0xc0001f5600)
/home/faltyn/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
/home/faltyn/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0001f5600, 0x162a4f8, 0x2, 0xc00011a210)
/home/faltyn/go/pkg/mod/github.com/tendermint/tendermint@v0.33.9/libs/cli/setup.go:89 +0x3c
main.main()
/home/faltyn/core/cmd/terracli/main.go:81 +0x39d
```

**To Reproduce**
`terracli keys add faltyn`

**Context & versions**
Environment:
- Ubuntu 20.10 on AWS EC2 r5.xlarge
- go version 16.3 
- golangci-lint version 1.39.0

**Similar Bugs**
Similar bug to this [issue](https://github.com/terra-money/core/issues/389).

**Comment by hanjukim** [comment]
Can you try to checkout v0.4.6? What is the output of `terracli version --long` The commit hash should be `c39ed2804dbb625c283d1cd11fac8d3bc79ff328`
