### ISSUE TITLE
[BUG] 0.5.0 cannot start

### ISSUE THREAD

**Issue by vae520283995** [terra-money/core#533]
**Describe the bug**
```
10:41AM INF starting ABCI with Tendermint
10:41AM INF Starting multiAppConn service impl=multiAppConn module=proxy
10:41AM INF Starting localClient service connection=query impl=localClient module=abci-client
10:41AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
10:41AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
10:41AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
10:41AM INF Starting EventBus service impl=EventBus module=events
10:41AM INF Starting PubSub service impl=PubSub module=pubsub
10:41AM INF Starting IndexerService service impl=IndexerService module=txindex
10:41AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=0.5.0
10:41AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
panic: Any JSON doesn't have '@type'

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0xc001182570, 0xc0188b4000, 0x151f91eb, 0x151fa000, 0x26ec5e0, 0xc000526040)
	github.com/cosmos/cosmos-sdk@v0.43.0/codec/proto_codec.go:176 +0x98
github.com/cosmos/cosmos-sdk/x/auth.AppModule.InitGenesis(0x26e26b8, 0xc0010fc230, 0x2718cd8, 0xc001182570, 0x2718cd8, 0xc001182570, 0xc00058fd38, 0x26e26b8, 0xc0010fc2a0, 0x26e2708, ...)
	github.com/cosmos/cosmos-sdk@v0.43.0/x/auth/module.go:143 +0xa4
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc001176af0, 0x2701288, 0xc000052100, 0x271b8c0, 0xc0000d63c0, 0x0, 0x0, 0xc000cba120, 0xa, 0x0, ...)
	github.com/cosmos/cosmos-sdk@v0.43.0/types/module/module.go:306 +0x2b5
github.com/terra-money/core/app.(*TerraApp).InitChainer(0xc0010ebb00, 0x2701288, 0xc000052100, 0x271b8c0, 0xc0000d63c0, 0x0, 0x0, 0xc000cba120, 0xa, 0x0, ...)
	github.com/terra-money/core/app/app.go:607 +0x170
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0000da1a0, 0x0, 0xed70a961a, 0x0, 0xc000cba120, 0xa, 0xc001492660, 0xc0001c4580, 0x37, 0x37, ...)
	github.com/cosmos/cosmos-sdk@v0.43.0/baseapp/abci.go:62 +0x315
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc0010d7d40, 0x0, 0xed70a961a, 0x0, 0xc000cba120, 0xa, 0xc001492660, 0xc0001c4580, 0x37, 0x37, ...)
	github.com/tendermint/tendermint@v0.34.11/abci/client/local_client.go:266 +0x115
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc000d56bc0, 0x0, 0xed70a961a, 0x0, 0xc000cba120, 0xa, 0xc001492660, 0xc0001c4580, 0x37, 0x37, ...)
	github.com/tendermint/tendermint@v0.34.11/proxy/app_conn.go:77 +0x78
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc00057dc18, 0xb, 0x0, 0x1fa9222, 0x7, 0xc000cba120, 0xa, 0x1, 0x0, 0x0, ...)
	github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:319 +0x655
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc00057dc18, 0x271cb28, 0xc000556000, 0x1f4, 0xc0014d68d0)
	github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:268 +0x458
github.com/tendermint/tendermint/node.doHandshake(0x2718798, 0xc001146000, 0xb, 0x0, 0x1fa9222, 0x7, 0xc000cba120, 0xa, 0x1, 0x0, ...)
	github.com/tendermint/tendermint@v0.34.11/node/node.go:308 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc0011c2dc0, 0x26f62a0, 0xc00002f180, 0xc0011470a0, 0x26be380, 0xc0005cda58, 0xc001147110, 0x2491cb8, 0xc001147210, 0x2701f38, ...)
```

**To Reproduce**
terrad start

**Context & versions**
0.5.0

**Comment by vae520283995** [comment]
The same steps, 0.4.6 works well

**Comment by YunSuk-Yeo** [comment]
Can you try this after whole resetting the env? like delete the TERRA_HOME dir and re-init the home folder

**Comment by vae520283995** [comment]
My steps
v0.4.6
```
1. git clone -b v0.4.6 https://github.com/terra-money/core
2. cd core && make install
3. terrad version --long
name: terra
server_name: terrad
client_name: terracli
version: 0.4.6
commit: c39ed2804dbb625c283d1cd11fac8d3bc79ff328
build_tags: netgo,ledger
go: go version go1.16.5 linux/amd64
4. terrad init test --home /data/terra/v0.4.6
5. curl https://columbus-genesis.s3-ap-northeast-1.amazonaws.com/columbus-4-genesis.json > /data/terra/v0.4.6/config/genesis.json
6. terrad start --home /data/terra/v0.4.6
```

v0.5.0
```
1. git clone -b v0.5.0 https://github.com/terra-money/core
2. cd core && make install
3. terrad version --long
name: terra
server_name: terrad
version: 0.5.0
commit: d6037b9a12c8bf6b09fe861c8ad93456aac5eebb
build_tags: netgo,ledger
go: go version go1.16.5 linux/amd64
4. terrad init test --home /data/terra/v0.5.0
5. curl https://columbus-genesis.s3-ap-northeast-1.amazonaws.com/columbus-4-genesis.json > /data/terra/v0.5.0/config/genesis.json
6. terrad start --home /data/terra/v0.5.0
```
```
terrad start --home /data/terra/v0.5.0
8:57AM INF starting ABCI with Tendermint
8:57AM INF Starting multiAppConn service impl=multiAppConn module=proxy
8:57AM INF Starting localClient service connection=query impl=localClient module=abci-client
8:57AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
8:57AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
8:57AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
8:57AM INF Starting EventBus service impl=EventBus module=events
8:57AM INF Starting PubSub service impl=PubSub module=pubsub
8:57AM INF Starting IndexerService service impl=IndexerService module=txindex
8:57AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=0.5.0
8:57AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
panic: Any JSON doesn't have '@type'

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0xc00111edc0, 0xc0ca332000, 0x151f91eb, 0x151fa000, 0x26eb5c0, 0xc000022000)
	github.com/cosmos/cosmos-sdk@v0.43.0/codec/proto_codec.go:176 +0x98
github.com/cosmos/cosmos-sdk/x/auth.AppModule.InitGenesis(0x26e1698, 0xc0010e4430, 0x2717cb8, 0xc00111edc0, 0x2717cb8, 0xc00111edc0, 0xc000119988, 0x26e1698, 0xc0010e4540, 0x26e16e8, ...)
	github.com/cosmos/cosmos-sdk@v0.43.0/x/auth/module.go:143 +0xa4
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc0001f4150, 0x2700268, 0xc000054100, 0x271a8a0, 0xc00017df80, 0x0, 0x0, 0xc000696600, 0xa, 0x0, ...)
	github.com/cosmos/cosmos-sdk@v0.43.0/types/module/module.go:306 +0x2b5
github.com/terra-money/core/app.(*TerraApp).InitChainer(0xc00109bb00, 0x2700268, 0xc000054100, 0x271a8a0, 0xc00017df80, 0x0, 0x0, 0xc000696600, 0xa, 0x0, ...)
	github.com/terra-money/core/app/app.go:607 +0x170
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0000da1a0, 0x0, 0xed70a961a, 0x0, 0xc000696600, 0xa, 0xc0013ba900, 0xc0001c6580, 0x37, 0x37, ...)
	github.com/cosmos/cosmos-sdk@v0.43.0/baseapp/abci.go:62 +0x315
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc00073fb60, 0x0, 0xed70a961a, 0x0, 0xc000696600, 0xa, 0xc0013ba900, 0xc0001c6580, 0x37, 0x37, ...)
	github.com/tendermint/tendermint@v0.34.11/abci/client/local_client.go:266 +0x115
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc00111ef30, 0x0, 0xed70a961a, 0x0, 0xc000696600, 0xa, 0xc0013ba900, 0xc0001c6580, 0x37, 0x37, ...)
	github.com/tendermint/tendermint@v0.34.11/proxy/app_conn.go:77 +0x78
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc0005bdc18, 0xb, 0x0, 0x1fa8262, 0x7, 0xc000696600, 0xa, 0x1, 0x0, 0x0, ...)
	github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:319 +0x655
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0005bdc18, 0x271bb08, 0xc000620000, 0x1f4, 0xc0005676b0)
	github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:268 +0x458
github.com/tendermint/tendermint/node.doHandshake(0x2717778, 0xc000ef4870, 0xb, 0x0, 0x1fa8262, 0x7, 0xc000696600, 0xa, 0x1, 0x0, ...)
	github.com/tendermint/tendermint@v0.34.11/node/node.go:308 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc0011808c0, 0x26f5280, 0xc00054cf00, 0xc00111edf0, 0x26bd360, 0xc0012dd998, 0xc00111ee60, 0x2490cd8, 0xc00111ef50, 0x2700f18, ...)
	github.com/tendermint/tendermint@v0.34.11/node/node.go:715 +0x20e5
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc0011a5720, 0x0, 0x0, 0x0, 0x2725078, 0xc00125ad20, 0x0, 0x0, 0x270a4f0, 0xc00111edc0, ...)
	github.com/cosmos/cosmos-sdk@v0.43.0/server/start.go:263 +0x685
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc001193180, 0xc0011a5860, 0x0, 0x2, 0x0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.43.0/server/start.go:129 +0x209
github.com/spf13/cobra.(*Command).execute(0xc001193180, 0xc0011a5840, 0x2, 0x2, 0xc001193180, 0xc0011a5840)
	github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000769900, 0x0, 0x0, 0xc0010f0df0)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000769900, 0xc0010f0df0, 0xc, 0x271d8b8, 0xc00111edc0)
	github.com/cosmos/cosmos-sdk@v0.43.0/server/cmd/execute.go:36 +0x285
main.main()
	github.com/terra-money/core/cmd/terrad/main.go:15 +0x45
```

**Comment by vae520283995** [comment]
@YunSuk-Yeo

**Comment by YunSuk-Yeo** [comment]
hmm we just need to download new bombay-9 genesis without v0.4.6 steps 

https://github.com/terra-money/testnet/tree/master/bombay-9#how-to-setup

**Comment by vae520283995** [comment]
> hmm you just need to download new bombay-9 genesis without v0.4.6 steps

Can v0.5.0 not be launched on the mainnet?

**Comment by YunSuk-Yeo** [comment]
yea that is only for bombay and columbus-5 network
