### ISSUE TITLE
[BUG] panic: proto: Int64Value: wiretype end group for non-group

### ISSUE THREAD

**Issue by xiaobaiskill** [terra-money/core#559]
**Describe the bug**
```
i started terra when I updated Terra to 0.5.3. 

command:
/usr/bin/terrad start --home /root/terra-data/terra
```

**log**
```
11:14AM INF starting ABCI with Tendermint
panic: proto: Int64Value: wiretype end group for non-group

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/store/rootmulti.getLatestVersion(0x271f1c0, 0xc0005901c0, 0x10)
        github.com/cosmos/cosmos-sdk@v0.44.0/store/rootmulti/store.go:940 +0x11c
github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).LoadLatestVersion(0xc000142460, 0x10, 0x7fbcecfe85b8)
        github.com/cosmos/cosmos-sdk@v0.44.0/store/rootmulti/store.go:162 +0x37
github.com/cosmos/cosmos-sdk/baseapp.DefaultStoreLoader(0x2728238, 0xc000142460, 0x0, 0xc00a29cb50)
        github.com/cosmos/cosmos-sdk@v0.44.0/baseapp/baseapp.go:273 +0x34
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).LoadLatestVersion(0xc0005661a0, 0xc00a255100, 0x7fbc98447518)
        github.com/cosmos/cosmos-sdk@v0.44.0/baseapp/baseapp.go:263 +0x42
github.com/terra-money/core/app.NewTerraApp(0x27065f8, 0xc00058eea0, 0x271f1c0, 0xc0005901c0, 0x0, 0x0, 0x1, 0xc00a1d8f00, 0x7ffea81ba734, 0x16, ...)
        github.com/terra-money/core/app/app.go:577 +0x9c45
main.appCreator.newApp(0x270fd38, 0xc000161b00, 0x27230b8, 0xc001257000, 0x27187d8, 0xc000fd1b00, 0xc0005917a8, 0x27065f8, 0xc00058eea0, 0x271f1c0, ...)
        github.com/terra-money/core/cmd/terrad/root.go:214 +0x9d5
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc0012d57a0, 0x0, 0x0, 0x0, 0x272a9d8, 0xc0013f8570, 0x0, 0x0, 0x270fcf0, 0xc001257000,...)
        github.com/cosmos/cosmos-sdk@v0.44.0/server/start.go:255 +0x2df
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0012cb400, 0xc0012d58e0, 0x0, 0x2, 0x0, 0x0)
        github.com/cosmos/cosmos-sdk@v0.44.0/server/start.go:129 +0x209
github.com/spf13/cobra.(*Command).execute(0xc0012cb400, 0xc0012d58c0, 0x2, 0x2, 0xc0012cb400, 0xc0012d58c0)
        github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000f3bb80, 0x0, 0x0, 0xc001232910)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000f3bb80, 0xc001232910, 0xc, 0x27230b8, 0xc001257000)
        github.com/cosmos/cosmos-sdk@v0.44.0/server/cmd/execute.go:36 +0x285
main.main()
        github.com/terra-money/core/cmd/terrad/main.go:15 +0x45
```

**versions**
```
name: terra
server_name: terrad
version: 0.5.3
commit: 9d1edccc14b6362ef30b7372a205646243337b88
build_tags: netgo,ledger
go: go version go1.16.5 linux/amd64
```

**Comment by hanjukim** [comment]
with which genesis? what network are you trying to join?

**Comment by begetan** [comment]
We have a similar error for 0.5.3 with the genesis file for bombay-11

`2:11PM ERR dialing failed (attempts: 13): auth failure: secret conn failed: proto: BytesValue: wiretype end group for non-group addr={"id":"0393c19b176d1cf8bc560c5a8fa990301deb1a7e","ip":"135.181.188.20","port":26656} module=pex`

**Comment by masayil** [comment]
after upgrade to columbus-5 mainnet ,v0.5.5. I have the same problem.

**Comment by YunSuk-Yeo** [comment]
First error can be occur with wrong genesis(previous network genesis) 
and Tendermint dial errors are common, that is just unexpected the response I think.
