### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by jadechip** [terra-money/core#605]
**Describe the bug**

Hello everyone 👋
I am trying to setup terrad and sync with Mainnet, which I take is columbus-5... 
but I am running into the following error:

```
panic: Any JSON doesn't have '@type'

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0xc0011eb780, 0xc018d34000, 0x151f91eb, 0x151fa000, 0x2e0b640, 0xc001280040)
	github.com/cosmos/cosmos-sdk@v0.44.2/codec/proto_codec.go:176 +0x98
github.com/cosmos/cosmos-sdk/x/auth.AppModule.InitGenesis(0x2e01670, 0xc001369a20, 0x2e383f8, 0xc0011eb780, 0x2e383f8, 0xc0011eb780, 0xc0011fe210, 0x2e01670, 0xc001369a90, 0x2e016c0, ...)
	github.com/cosmos/cosmos-sdk@v0.44.2/x/auth/module.go:143 +0xa4
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc00122c310, 0x2e20448, 0xc000056068, 0x2e3b0e0, 0xc0000d8b40, 0x0, 0x0, 0xc0005265c0, 0xa, 0x0, ...)
	github.com/cosmos/cosmos-sdk@v0.44.2/types/module/module.go:307 +0x2b5
github.com/terra-money/core/app.(*TerraApp).InitChainer(0xc00116bb00, 0x2e20448, 0xc000056068, 0x2e3b0e0, 0xc0000d8b40, 0x0, 0x0, 0xc0005265c0, 0xa, 0x0, ...)
	github.com/terra-money/core/app/app.go:602 +0x170
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc001302000, 0x0, 0xed70a961a, 0x0, 0xc0005265c0, 0xa, 0xc000592780, 0xc0001c6000, 0x37, 0x37, ...)
	github.com/cosmos/cosmos-sdk@v0.44.2/baseapp/abci.go:62 +0x315
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc001428660, 0x0, 0xed70a961a, 0x0, 0xc0005265c0, 0xa, 0xc000592780, 0xc0001c6000, 0x37, 0x37, ...)
	github.com/tendermint/tendermint@v0.34.13/abci/client/local_client.go:274 +0x115
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc0013588f0, 0x0, 0xed70a961a, 0x0, 0xc0005265c0, 0xa, 0xc000592780, 0xc0001c6000, 0x37, 0x37, ...)
	github.com/tendermint/tendermint@v0.34.13/proxy/app_conn.go:77 +0x78
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc0005d1c18, 0xb, 0x0, 0x26c0548, 0x7, 0xc0005265c0, 0xa, 0x1, 0x0, 0x0, ...)
	github.com/tendermint/tendermint@v0.34.13/consensus/replay.go:319 +0x655
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0005d1c18, 0x2e3c3e8, 0xc0005ac000, 0x1f4, 0xc000f7c120)
	github.com/tendermint/tendermint@v0.34.13/consensus/replay.go:268 +0x458
github.com/tendermint/tendermint/node.doHandshake(0x2e37eb8, 0xc001187590, 0xb, 0x0, 0x26c0548, 0x7, 0xc0005265c0, 0xa, 0x1, 0x0, ...)
	github.com/tendermint/tendermint@v0.34.13/node/node.go:322 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc001233680, 0x2e15300, 0xc0005b8780, 0xc001186460, 0x2ddd260, 0xc0005ab980, 0xc0011864d0, 0x2bad5c8, 0xc001186620, 0x2e210c0, ...)
	github.com/tendermint/tendermint@v0.34.13/node/node.go:730 +0x2105
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc001239b60, 0x0, 0x0, 0x0, 0x2e45b58, 0xc0012fd590, 0x0, 0x0, 0x2e2ac70, 0xc0011eb780, ...)
	github.com/cosmos/cosmos-sdk@v0.44.2/server/start.go:263 +0x685
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00124bb80, 0xc0012d3c40, 0x0, 0x1, 0x0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.44.2/server/start.go:129 +0x209
github.com/spf13/cobra.(*Command).execute(0xc00124bb80, 0xc0012d3c30, 0x1, 0x1, 0xc00124bb80, 0xc0012d3c30)
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000fe2c80, 0x0, 0x0, 0xc0006978a8)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.2.1/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000fe2c80, 0xc0006978a8, 0x12, 0x2e3e238, 0xc0011eb780)
	github.com/cosmos/cosmos-sdk@v0.44.2/server/cmd/execute.go:36 +0x285
main.main()
	github.com/terra-money/core/cmd/terrad/main.go:15 +0x45
```

I am using Golang version `1.16.10` and Terra version `0.5.10`, and here is the genesis file I am downloading. 
`https://columbus-genesis.s3-ap-northeast-1.amazonaws.com/columbus-5-genesis.json`

In my Dockerfile I also download the following version of wasmvm.

```
ADD https://github.com/CosmWasm/wasmvm/releases/download/v0.16.1/libwasmvm_muslc.a /lib/libwasmvm_muslc.a
RUN sha256sum /lib/libwasmvm_muslc.a | grep 0e62296b9f24cf3a05f8513f99cee536c7087079855ea6ffb4f89b35eccdaa66
```

Please advise.

**Comment by YunSuk-Yeo** [comment]
your genesis file seems wrong or your data directly has wrong data. 
so try `$ terrad unsafe-reset-all` and try start again

**Comment by jadechip** [comment]
I see, I'll try running that command. Am I downloading the genesis file for Columbus from the right location?
I couldn't find a link in the docs.

**Comment by jadechip** [comment]
I've also tried using `terrad init`, here is what I am currently doing now:
```
git clone https://github.com/terra-money/core.git . \
    && curl -Lo /tmp/terra/genesis.json https://columbus-genesis.s3-ap-northeast-1.amazonaws.com/columbus-5-genesis.json \
    && make build
    
terrad init terra-0 --chain-id columbus-5 --home /home/terra --overwrite

terrad start --home /home/terra
```

**Comment by YunSuk-Yeo** [comment]
seems you download the genesis, place the genesis into the right location

https://docs.terra.money/How-to/Run-a-full-Terra-node/Join-public-network.html#download-the-genesis-file

```sh
wget https://columbus-genesis.s3.ap-northeast-1.amazonaws.com/columbus-5-genesis.json -O /home/terra/config/genesis.json

terrad unsafe-reset-all --home /home/terra

terrad start --home /home/terra

```

**Comment by YunSuk-Yeo** [comment]
close inactive issue
