### ISSUE TITLE
[BUG] Panic in `terrad export`

### ISSUE THREAD

**Issue by joe-bowman** [terra-money/core#606]
**Describe the bug**
`terrad export --height XXX` panics.

**To Reproduce**
`terra terrad export --height=5257270 > terra_snapshot.json`.

Results in the following output:
```
panic: Null/Nil argument: checksum

goroutine 1 [running]:
github.com/terra-money/core/x/wasm.ExportGenesis({{0x23641e8, 0xc000052048}, {0x23914e0, 0xc01658a200}, {{0x0, 0x0}, {0x0, 0x0}, 0x503836, {0x0, ...}, ...}, ...}, ...)
	github.com/terra-money/core/x/wasm/genesis.go:67 +0x799
github.com/terra-money/core/x/wasm.AppModule.ExportGenesis({{{0x2397bf8, 0xc0012c4e30}}, {{0x232f070, 0xc001e4dd20}, {0x238c518, 0xc0012c4e30}, {{0x238c518, 0xc0012c4e30}, 0xc000011d28, {0x232f070, ...}, ...}, ...}, ...}, ...)
	github.com/terra-money/core/x/wasm/module.go:158 +0x9b
github.com/cosmos/cosmos-sdk/types/module.(*Manager).ExportGenesis(_, {{0x23641e8, 0xc000052048}, {0x23914e0, 0xc01658a200}, {{0x0, 0x0}, {0x0, 0x0}, 0x503836, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.44.2/types/module/module.go:328 +0x125
github.com/terra-money/core/app.(*TerraApp).ExportAppStateAndValidators(0xc001227b00, 0x0, {0x3302f78, 0x0, 0x0})
	github.com/terra-money/core/app/export.go:34 +0x20f
main.appCreator.appExport({{{0x236d6f8, 0xc0012ca390}, {0x2397bf8, 0xc0012c4e30}, {0x237ffb8, 0xc00122d100}, 0xc000011d28}}, {0x2364e98, 0xc001435aa0}, {0x238d218, ...}, ...)
	github.com/terra-money/core/cmd/terrad/root.go:255 +0x44a
github.com/cosmos/cosmos-sdk/server.ExportCmd.func1(0xc00131d680, {0xc0013b52f0, 0x0, 0x1})
	github.com/cosmos/cosmos-sdk@v0.44.2/server/export.go:71 +0x31c
github.com/spf13/cobra.(*Command).execute(0xc00131d680, {0xc0013b52e0, 0x1, 0x1})
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc001234280)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.2.1/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0, {0xc001231d70, 0xd})
	github.com/cosmos/cosmos-sdk@v0.44.2/server/cmd/execute.go:36 +0x1eb
main.main()
	github.com/terra-money/core/cmd/terrad/main.go:15 +0x2c
```

**Context & versions**
terrad 0.5.10 and 0.5.11

**Comment by joe-bowman** [comment]
Having dug into this a little more, 

https://github.com/terra-money/core/blob/19b75bfd60f7623bf4ef8919ab0e52d73ad99643/x/wasm/keeper/keeper.go#L210

expects the argument 'codeHash' (a checksum of the code to load from the cache), but in this case, the value passed appears to be `nil`. Is it possible we have some bad state here?

**Comment by YunSuk-Yeo** [comment]
@joe-bowman Thanks for reporting. I will fix this.
