### ISSUE TITLE
BINARY UPDATED BEFORE TRIGGER! UPGRADE "2.1.0" - in binary but not executed on chain

### ISSUE THREAD

**Issue by vae520283995** [terra-money/core#64]
```
ul 27 04:45:30 ip-172-31-27-151 terrad[286607]: 4:45AM INF starting node with ABCI Tendermint in-process
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: 4:45AM INF Starting multiAppConn service impl=multiAppConn module=proxy
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: 4:45AM INF Starting localClient service connection=query impl=localClient module=abci-client
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: 4:45AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: 4:45AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: 4:45AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: 4:45AM INF Starting EventBus service impl=EventBus module=events
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: 4:45AM INF Starting PubSub service impl=PubSub module=pubsub
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: 4:45AM INF Starting IndexerService service impl=IndexerService module=txindex
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: 4:45AM INF ABCI Handshake App Info hash="����\n�����\x1aՓ\x1c�uo���\x16%?�[�\vYue�E" height=865312 module=consensus protocol-version=0 software-version=v2.1.0
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: 4:45AM INF ABCI Replay Blocks appHeight=865312 module=consensus stateHeight=865312 storeHeight=865313
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: 4:45AM INF Replay last block using real app module=consensus
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: 4:45AM ERR BINARY UPDATED BEFORE TRIGGER! UPGRADE "2.1.0" - in binary but not executed on chain
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: panic: BINARY UPDATED BEFORE TRIGGER! UPGRADE "2.1.0" - in binary but not executed on chain
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: goroutine 1 [running]:
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{0x7ffd3e3cdf06, 0xb}, 0xc0012a2f00, {0x278c948, 0xc0014605d0}, {0x27ab390, 0xc001175e90}, 0xc0012a2db0, {0x0, 0x0}, ...}, ...)
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/cosmos/cosmos-sdk@v0.45.4/x/upgrade/abci.go:85 +0xdc7
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/cosmos/cosmos-sdk@v0.45.4/x/upgrade/module.go:130
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x27a0018, 0xc000052090}, {0x27acb20, 0xc00e303cc0}, {{0xb, 0x0}, {0xc001633460, 0x9}, 0xd3421, ...}, ...}, ...)
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/cosmos/cosmos-sdk@v0.45.4/types/module/module.go:479 +0x3a2
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/terra-money/core/v2/app.(*TerraApp).BeginBlocker(_, {{0x27a0018, 0xc000052090}, {0x27acb20, 0xc00e303cc0}, {{0xb, 0x0}, {0xc001633460, 0x9}, 0xd3421, ...}, ...}, ...)
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/terra-money/core/v2/app/app.go:671 +0x85
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc01a7ca7a0, 0x20, 0x20}, {{0xb, 0x0}, {0xc001633460, 0x9}, 0xd3421, {0x16cbedf9, ...}, ...}, ...})
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:194 +0x97c
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc01a7ca7a0, 0x20, 0x20}, {{0xb, 0x0}, {0xc001633460, 0x9}, 0xd3421, {0x16cbedf9, ...}, ...}, ...})
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:280 +0x118
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc01a7ca7a0, 0x20, 0x20}, {{0xb, 0x0}, {0xc001633460, 0x9}, 0xd3421, {0x16cbedf9, ...}, ...}, ...})
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:81 +0x55
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x27a1048?, 0xc022ead6e0}, {0x27a6388, 0xc001428ad0}, 0xc00103cf00, {0x27abda0, 0xc00155c8e0}, 0xd3420?)
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/tendermint/tendermint@v0.34.19/state/execution.go:307 +0x3dd
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc03ad98010, 0x10}}, {0xc03ad98020, 0x9}, 0x1, 0xd3420, {{0xc001280000, ...}, ...}, ...}, ...)
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/tendermint/tendermint@v0.34.19/state/execution.go:140 +0x171
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc03ad98010, 0x10}}, {0xc03ad98020, 0x9}, 0x1, 0xd3420, {{0xc001280000, ...}, ...}, ...}, ...)
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:503 +0x23c
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc03ad98010, 0x10}}, {0xc03ad98020, 0x9}, 0x1, 0xd3420, {{0xc001280000, ...}, ...}, ...}, ...)
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:416 +0x7ae
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc02a351fd0, {0x27ad380, 0xc000ec3ad0})
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc03ad98010, 0x10}}, {0xc03ad98020, 0x9}, 0x1, 0xd3420, ...}, ...)
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/tendermint/tendermint/node.NewNode(0xc001298c80, {0x279cdf0, 0xc0005be500}, 0xc000f21ef0, {0x2787be0, 0xc0679fb6f8}, 0x0?, 0x0?, 0xc0000cd8d0, {0x27a1048, ...}, ...)
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x577
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x27b3d48, 0xc0013753b0}, {0x0, 0x0}, {0x27a4260, 0xc001175e90}, ...}, ...)
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:272 +0x7db
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0012aef00?, {0xc001374750?, 0x0?, 0x3?})
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:126 +0x169
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/spf13/cobra.(*Command).execute(0xc0012aef00, {0xc0013746f0, 0x3, 0x3})
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/spf13/cobra.(*Command).ExecuteC(0xc001294500)
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/spf13/cobra.(*Command).Execute(...)
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/spf13/cobra@v1.4.0/command.go:902
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/spf13/cobra.(*Command).ExecuteContext(...)
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/spf13/cobra@v1.4.0/command.go:895
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc000f4dfe0, 0xc})
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/cosmos/cosmos-sdk@v0.45.4/server/cmd/execute.go:36 +0x1eb
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]: main.main()
Jul 27 04:45:34 ip-172-31-27-151 terrad[286607]:         github.com/terra-money/core/v2/cmd/terrad/main.go:15 +0x2c
```

**Comment by vae520283995** [comment]
Rolling back to v2.0.1 works fine

**Comment by vae520283995** [comment]
@YunSuk-Yeo @hanjukim

**Comment by YunSuk-Yeo** [comment]
now proposal passed https://station.terra.money/proposal/894

so you need to update your node to v2.1.0 or main at height `890000`

**Comment by vae520283995** [comment]
> now proposal passed https://station.terra.money/proposal/894
> 
> so you need to update your node to v2.1.0 or main at height `890000`

@YunSuk-Yeo 
Now i update to v2.1.0 it shows the above error, with v2.0.1 it works fine, when should i update to v2.1.0

**Comment by YunSuk-Yeo** [comment]
> > now proposal passed https://station.terra.money/proposal/894
> > so you need to update your node to v2.1.0 or main at height `890000`
> 
> @YunSuk-Yeo Now i update to v2.1.0 it shows the above error, with v2.0.1 it works fine, when should i update to v2.1.0

You need to update your node to v2.1.0 or main when height reach `890000`

**Comment by vae520283995** [comment]
> You need to update your node to v2.1.0 or main when height reach `890000`

I thought main was mainnet, it turned out to be the main branch, thank you
