### ISSUE TITLE
[BUG] node sync fail (wrong Block.Header.AppHash)

### ISSUE THREAD

**Issue by MeNoln** [terra-money/core#640]
**Describe the bug**
After bombay-12 softfork my testnet node failed. As suggested I've downloaded a snapshot from 26.12. After restarting the node I see the same error. Logs:
```
2:08PM INF committed state app_hash=2AEF769C108309CD3CEAF24E09AAAFDB6E7D8E2CE1B580D87530899297EB9BF3 height=7152413 module=state num_txs=1
2:08PM INF indexed block height=7152413 module=txindex
2:08PM INF minted coins from module account amount=1054451uluna from=mint module=x/bank
2:08PM INF executed block height=7152414 module=state num_invalid_txs=0 num_valid_txs=11
2:08PM INF commit synced commit=436F6D6D697449447B5B31353420313420313330203131382036382034302031363020313132203136392031393020313732203137392034203338203937203131372032332032303820313231203136322032343220333520313733203739203334203235332035302031392031322031383320323431203234325D3A3644323331457D
2:08PM INF committed state app_hash=9A0E82764428A070A9BEACB30426617517D079A2F223AD4F22FD32130CB7F1F2 height=7152414 module=state num_txs=11
panic: Failed to process committed block (7152415:E0F20DA8206CF9C3E792E9333F15B393A015D9C09296D5B53A60520C3F0DE6A4): wrong Block.Header.AppHash.  Expected 9A0E82764428A070A9BEACB30426617517D079A2F223AD4F22FD32130CB7F1F2, got AC97667AF61AC0A5499FEC2C3805E6A6C2BF666F85D4CCF5C0714B6E43D3F519

goroutine 71 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000c79a40, 0x0)
	github.com/tendermint/tendermint@v0.34.13/blockchain/v0/reactor.go:401 +0x15bf
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	github.com/tendermint/tendermint@v0.34.13/blockchain/v0/reactor.go:110 +0x8c

```

**Context & versions**
terrad version: 0.5.11

Can you please suggest any instructions on how to fix this?
I will also try to download a snapshot from 27.12 and try to re-sync.

**Comment by Vritra4** [comment]
update terrad to 0.5.14 please.

**Comment by faddat** [comment]
would you accept a PR that implements Tendermint's single-block rollback feature?

This sync fail is actually what's keeping me from providing a pruned rocksdb snapshot.

**Comment by MeNoln** [comment]
> update terrad to 0.5.14 please.

Thanks from TeFiLuck team, that's solved our issue, closing it :+1:
