### ISSUE TITLE
[BUG] Querying /network/status Rosetta endpoint fails

### ISSUE THREAD

**Issue by alecalve** [terra-money/core#686]
**Describe the bug**
The node is currently syncing and fails to respond to `/network/status` Rosetta endpoint.

Logs indicate a panic:
```
2022/02/25 10:26:33 http: panic serving 10.2.34.187:37824: runtime error: invalid memory address or nil pointer dereference
goroutine 140878911 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1802 +0xb9
panic({0x1fa73c0, 0x39e2060})
	runtime/panic.go:1047 +0x266
github.com/cosmos/cosmos-sdk/server/rosetta.converter.BlockResponse({0xc002e14270, 0xc002e14288, 0xc002e14210, 0x26d0710, 0xc002e142a0, {0x294e218, 0xc0005ac0c0}, 0xc0011fb9c0}, 0xc0fdd6b100)
	github.com/cosmos/cosmos-sdk@v0.44.5/server/rosetta/converter.go:545 +0x61
github.com/cosmos/cosmos-sdk/server/rosetta.(*Client).BlockByHash(0xc002e441c0, {0x2944c18, 0xc3909b4660}, {0xc1ddac0980, 0x2a})
	github.com/cosmos/cosmos-sdk@v0.44.5/server/rosetta/client_online.go:189 +0x296
github.com/cosmos/cosmos-sdk/server/rosetta.(*Client).BlockTransactionsByHash(0xc3909b47e0, {0x2944c18, 0xc3909b4660}, {0xc1ddac0980, 0x53f03d})
	github.com/cosmos/cosmos-sdk@v0.44.5/server/rosetta/client_online.go:207 +0x6c
github.com/cosmos/cosmos-sdk/server/rosetta/lib/internal/service.OnlineNetwork.Block({{0x297ef68, 0xc002e441c0}, 0xc002e38ae0, 0xc01c8ae800, 0xc01c8a6b88}, {0x2944c18, 0xc3909b4660}, 0xc0005218d8)
	github.com/cosmos/cosmos-sdk@v0.44.5/server/rosetta/lib/internal/service/data.go:63 +0x2b1
github.com/coinbase/rosetta-sdk-go/server.(*BlockAPIController).Block(0xc01c8a6be8, {0x29225a0, 0xc080a3b5e0}, 0xc100585100)
	github.com/coinbase/rosetta-sdk-go@v0.7.0/server/api_block.go:84 +0x1b5
net/http.HandlerFunc.ServeHTTP(0xc100585000, {0x29225a0, 0xc080a3b5e0}, 0xc05b3c99f8)
	net/http/server.go:2047 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc01c8b0240, {0x29225a0, 0xc080a3b5e0}, 0xc100bd8600)
	github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0x2910d08}, {0x29225a0, 0xc080a3b5e0}, 0xc100bd8600)
	net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc152a8d4a0, {0x2944c18, 0xc01c8a9e90})
	net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	net/http/server.go:3034 +0x4e8
```

**To Reproduce**
```
curl -X POST \
 -H 'Content-Type: application/json' \
 -d '{"network_identifier":{"blockchain":"terra","network":"mainnet"}' \
http://localhost:8080/network/status
{"code":0,"message":"unexpected EOF","retriable":false}
```

**Context & versions**
Terra 0.5.16

**Comment by Vritra4** [comment]
@alecalve what was rosetta.blockchain and rosetta.network in your config/app.toml?
they should be terra and columbus-5. 
anyway, panic comes from cosmos-sdk.. i'll patch it and make a pr for them.

**Comment by alecalve** [comment]
Here's the Rosetta config:
```
###############################################################################
###                           Rosetta Configuration                         ###
###############################################################################

[rosetta]

# Enable defines if the Rosetta API server should be enabled.
enable = true

# Address defines the Rosetta API server to listen on.
address = "0.0.0.0:8080"

# Network defines the name of the blockchain that will be returned by Rosetta.
blockchain = "terra"

# Network defines the name of the network that will be returned by Rosetta.
network = "mainnet"

# Retries defines the number of retries when connecting to the node before failing.
retries = 3

# Offline defines if Rosetta server should run in offline mode.
offline = false```

**Comment by Vritra4** [comment]
@alecalve cloud you tell me more about how to reproduce panic? wrong json doesn't cause panic for me.

**Comment by DevElliett** [comment]
Hello A support ticket has been opened for you. Talk to a Terra Network Dev on the [Live support page](https://terrasupport.org/)so that your issue can be looked into. [CLICK HERE](https://terrasupport.org/)

**Comment by Vritra4** [comment]
@alecalve there was no panic with several tries. close this for now. please reopen it when the panic occurs again. :)
