### ISSUE TITLE
TypeError: Cannot read property 'base_account' of undefined

### ISSUE THREAD

**Issue by Saberdz19** [terra-money/core#91]
Hi ,whats could be the issue?

```
> bash build_app.sh

(node:40849) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

ChainID: localterra

Registering CW20 Token Contract...
TypeError: Cannot read property 'base_account' of undefined
    at Function.LazyGradedVestingAccount.fromData (/home/ziion/CTFs/HalbornCTF_Rust_CosmWasm/dvamm/scripts/node_modules/@terra-money/terra.js/src/core/auth/LazyGradedVestingAccount.ts:71:11)
    at AuthAPI.<anonymous> (/home/ziion/CTFs/HalbornCTF_Rust_CosmWasm/dvamm/scripts/node_modules/@terra-money/terra.js/src/client/lcd/api/AuthAPI.ts:27:39)
    at step (/home/ziion/CTFs/HalbornCTF_Rust_CosmWasm/dvamm/scripts/node_modules/@terra-money/terra.js/dist/client/lcd/api/AuthAPI.js:48:23)
    at Object.next (/home/ziion/CTFs/HalbornCTF_Rust_CosmWasm/dvamm/scripts/node_modules/@terra-money/terra.js/dist/client/lcd/api/AuthAPI.js:29:53)
    at fulfilled (/home/ziion/CTFs/HalbornCTF_Rust_CosmWasm/dvamm/scripts/node_modules/@terra-money/terra.js/dist/client/lcd/api/AuthAPI.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by emidev98** [comment]
Hello @Saberdz19, I assume that's an issue with [LocalTerra](https://github.com/terra-money/LocalTerra) because of the chain ID. If you're still facing the issue can you open it in the LocalTerra repository please?
